### ISSUE TITLE
Support other codecs than just 'utf-8'

### ISSUE THREAD

**Issue by krayzpipes** [krayzpipes/txt-ferret#26]
The following stack trace shows what appears to be a non-utf-8 encoded file. Some options:
- Let the user define the codec to use.   <-- I like this one
- Automatically run through a list of codecs to try.

```python
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/some_user/venv/lib64/python3.6/site-packages/txtferret/cli.py", line 69, in bootstrap
    ferret.scan_file()
  File "/home/some_user/venv/lib64/python3.6/site-packages/txtferret/core.py", line 315, in scan_file
    for index, line in enumerate(rf):
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 1471: invalid continuation byte
"""

Traceback (most recent call last):
  File "/home/some_user/venv/bin/txtferret", line 11, in <module>
    sys.exit(main())
  File "/home/some_user/venv/lib64/python3.6/site-packages/txtferret/__init__.py", line 7, in main
    exit(cli())
  File "/home/some_user/venv/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/some_user/venv/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/some_user/venv/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/some_user/venv/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/some_user/venv/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/some_user/venv/lib64/python3.6/site-packages/txtferret/cli.py", line 190, in scan
    results = p.map(bootstrap, configs)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 1471: invalid continuation byte

```

**Comment by krayzpipes** [comment]
Currently, txtferret opens files as the default encoding (utf-8). Which if the encoding doesn't work, or it isn't utf-8, it presents problems.

If we read as bytes by default, and then automatically encode the filters from utf-8, then we remove the encoding issue of the file we're scanning. This now leaves an issue when decoding the filter, which we can resolve by adding another filter parameter to decode based on a specified encoding OR the default of utf-8.
