### ISSUE TITLE
GZIP support broken by substitute function

### ISSUE THREAD

**Issue by krayzpipes** [krayzpipes/txt-ferret#27]
Doh... GZIP support broken by substitute function.  substitute only replaces with a `str` object. There is no provision for replacing with an empty `b''` string.

This is why you should write integration tests.........

```python
Traceback (most recent call last):
  File "/home/some_user/venv/bin/txtferret", line 11, in <module>
    sys.exit(main())
  File "/home/some_user/venv/lib64/python3.6/site-packages/txtferret/__init__.py", line 7, in main
    exit(cli())
  File "/home/some_user/venv/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/some_user/venv/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/some_user/venv/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/some_user/venv/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/some_user/venv/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/some_user/venv/lib64/python3.6/site-packages/txtferret/cli.py", line 169, in scan
    result = bootstrap(config)
  File "/home/some_user/venv/lib64/python3.6/site-packages/txtferret/cli.py", line 69, in bootstrap
    ferret.scan_file()
  File "/home/some_user/venv/lib64/python3.6/site-packages/txtferret/core.py", line 326, in scan_file
    self._scan_non_delimited_line(line, index)
  File "/home/some_user/venv/lib64/python3.6/site-packages/txtferret/core.py", line 397, in _scan_non_delimited_line
    if not sanity_test(filter_, match):
  File "/home/some_user/venv/lib64/python3.6/site-packages/txtferret/core.py", line 468, in sanity_test
    _text = re.sub(filter_.substitute, "", text)
  File "/usr/lib64/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: sequence item 0: expected a bytes-like object, str found
```

Note: **_text = re.sub(filter_.substitute, "", text)**

**Comment by krayzpipes** [comment]
Problem is in `txtferret.core.sanity_test`:

```python

def sanity_test(filter_, text, sub=True, sanity_func=None):
    """Return bool depending on if text passes the sanity check.
    :param filter_: Filter object.
    :param text: The text being tested by the sanity check.
    :param sub: For future use, can be used to skip the substitution
        portion before passing text to sanity checks.
    :sanity_func: Used for tests.
    :return: True or False - Depending on if sanity check passed
        or not.
    """
    _sanity_checker = sanity_func or sanity_check

    if sub:
        _text = re.sub(filter_.substitute, "", text)
    else:
        _text = text

    for algorithm_name in filter_.sanity:

        if not _sanity_checker(algorithm_name, _text):
            return False
    return True

```
